### ISSUE TITLE
Explain the rationale for swapping `/` `,` `.` keys

### ISSUE THREAD

**Issue by rszyma** [Apsu/Canary#16]
The original qwerty keyboard has these keys in this order: `,` `.` `/`

Any reasons swapping them is recommended?

I'd say that having `.` and `enter` keys both on pinky is worse, since they often occur at the end of paragraphs.

**Comment by christoofar** [comment]
Canary-user here (ortho version, and occasionally rowstag as well).   Pinky-stress is a valid concern, but also the frequency that the pinky gets utilized has to be taken into account.   Obviously a sentence terminator like `?` appears less frequently than `.` does, but the comma appears far more often.    While the ring finger is a mushy-unwieldy beast, it can stand more of the use that the comma gives it.

Since `,` and `.` like to be together (though a lifetime of reinforced exposure, and because seeing shifted `<` and `>` is pleasing, _and_ because we have more dexterity in our pinky fingers, we have more control striking `.` and hitting it correctly than we do with the middle-finger in QWERTY.

The change is quite jarring, though.   Even on the ortho version.   I can tell you though after switching to it on March (it's now August), it does feel very natural and striking this punctuation feels more accurate and satisfying than it ever did on QWERTY.   Every time I reach for `.` my pinky is landing in the center-cup of the keycap instead of landing at the edges of the key, which I then have to quickly correct before pushing it down to register the keystroke.

**Comment by carlosvigil** [comment]
I also agree, it feels better.

**Comment by Apsu** [comment]
I agree with the above comments, but the actual original reason was that the `oe,` column is a rather large SFB increase (0.2-0.3% depending on corpus). It felt minor/natural enough in feel that I decided it was reasonable for the layout release.
